# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='mu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Menu'),
        ),
    ]
